var loop = ['loop', 'ran', 'self']

var musicList = [
  {
      name:'丑八怪',
      singer:'薛之谦',
      duration:'04:08',
      music:'丑八怪.mp3',
      imgPath:'薛之谦.png'
  },{
      name:'演员',
      singer:'薛之谦',
      duration:'04:22',
      music:'演员.mp3',
      imgPath:'薛之谦.png'
  },{
      name:'她来听我的演唱会',
      singer:'张学友',
      duration:'04:51',
      music:'她来听我的演唱会.mp3',
      imgPath:'张学友.png'
  },{
      name:'只愿一生爱一人',
      singer:'张学友',
      duration:'04:22',
      music:'只愿一生爱一人.mp3',
      imgPath:'张学友.png'
  }
]


var onlineList = [
  {
      name:'I Will Return',
      singer:'Skylar Grey',
      duration:'03:56',
      music:'I Will Return.mp3',
      imgPath:'fast5.png'
  },{
      name:'晴天',
      singer:'周杰伦',
      duration:'04:48',
      music:'晴天.mp3',
      imgPath:'周杰伦.png'
  },{
      name:'够钟',
      singer:'周柏豪',
      duration:'03:48',
      music:'够钟.mp3',
      imgPath:'周柏豪.png'
  },{
      name:'江南',
      singer:'林俊杰',
      duration:'04:28',
      music:'江南.mp3',
      imgPath:'林俊杰.png'
  },{
      name:'凡人歌',
      singer:'李宗盛',
      duration:'03:46',
      music:'凡人歌.mp3',
      imgPath:'李宗盛.png'
  }
]


var onlineReList = [
  {
      name:'I Will Return',
      singer:'Skylar Grey',
      duration:'03:56',
      music:'I Will Return.mp3',
      imgPath:'fast5.png'
  },{
      name:'朋友',
      singer:'谭咏麟',
      duration:'04:48',
      music:'朋友.mp3',
      imgPath:'谭咏麟.png'
  },{
      name:'够钟',
      singer:'周柏豪',
      duration:'03:48',
      music:'够钟.mp3',
      imgPath:'周柏豪.png'
  },{
      name:'南方姑娘',
      singer:'赵雷',
      duration:'03:56',
      music:'南方姑娘.mp3',
      imgPath:'赵雷.png'
  },
  {
      name:'南方姑娘',
      singer:'赵雷',
      duration:'03:56',
      music:'南方姑娘.mp3',
      imgPath:'赵雷.png'
  },
  {
      name:'南方姑娘',
      singer:'赵雷',
      duration:'03:56',
      music:'南方姑娘.mp3',
      imgPath:'赵雷.png'
  },
  {
      name:'南方姑娘',
      singer:'赵雷',
      duration:'03:56',
      music:'南方姑娘.mp3',
      imgPath:'赵雷.png'
  },
  {
      name:'南方姑娘',
      singer:'赵雷',
      duration:'03:56',
      music:'南方姑娘.mp3',
      imgPath:'赵雷.png'
  },
]

var singerList = [
  {
    name:'周杰伦',
    imgPath:'周杰伦.png',
  },
  {
    name:'李宗盛',
    imgPath:'李宗盛.png',
  },
  {
    name:'林俊杰',
    imgPath:'林俊杰.png',
  },
  {
    name:'谭咏麟',
    imgPath:'谭咏麟.png',
  },
  {
    name:'薛之谦',
    imgPath:'薛之谦.png',
  },
  {
    name:'张学友',
    imgPath:'张学友.png',
  },
  {
    name:'陈奕迅',
    imgPath:'陈奕迅.png',
  },
  {
    name:'赵雷',
    imgPath:'赵雷.png',
  },
]

var songBook = [
  [
    {
      name:'晴天',
      singer:'周杰伦',
      duration:'04:48',
      music:'晴天.mp3',
      imgPath:'周杰伦.png'
    },
    {
      name:'夜的第七章',
      singer:'周杰伦',
      duration:'03:48',
      music:'夜的第七章.mp3',
      imgPath:'周杰伦.png'
    },
    {
      name:'半岛铁盒',
      singer:'周杰伦',
      duration:'05:19',
      music:'半岛铁盒.mp3',
      imgPath:'周杰伦.png'
    },
    {
      name:'东风破',
      singer:'周杰伦',
      duration:'05:15',
      music:'东风破.mp3',
      imgPath:'周杰伦.png'
    },
  ],
  [
    {
      name:'凡人歌',
      singer:'李宗盛',
      duration:'03:46',
      music:'凡人歌.mp3',
      imgPath:'李宗盛.png'
    },
    {
      name:'鬼迷心窍',
      singer:'李宗盛',
      duration:'03:23',
      music:'鬼迷心窍.mp3',
      imgPath:'李宗盛.png'
    },
    {
      name:'不懂',
      singer:'李宗盛',
      duration:'03:04',
      music:'不懂.mp3',
      imgPath:'李宗盛.png'
    },
    {
      name:'问(live)',
      singer:'李宗盛',
      duration:'03:11',
      music:'问.mp3',
      imgPath:'李宗盛.png'
    },
  ],
  [
    {
      name:'江南',
      singer:'林俊杰',
      duration:'04:28',
      music:'江南.mp3',
      imgPath:'林俊杰.png'
    },
    {
      name:'她说',
      singer:'林俊杰',
      duration:'05:20',
      music:'她说.mp3',
      imgPath:'林俊杰.png'
    },
    {
      name:'爱笑的眼睛',
      singer:'林俊杰',
      duration:'04:13',
      music:'爱笑的眼睛.mp3',
      imgPath:'林俊杰.png'
    },
    {
      name:'当你',
      singer:'林俊杰',
      duration:'04:11',
      music:'当你.mp3',
      imgPath:'林俊杰.png'
    },
  ],
  [
    {
      name:'爱多一次痛一次',
      singer:'谭咏麟',
      duration:'04:16',
      music:'爱多一次痛一次.mp3',
      imgPath:'谭咏麟.png'
    },
    {
      name:'再见亦是泪',
      singer:'谭咏麟',
      duration:'04:30',
      music:'再见亦是泪.mp3',
      imgPath:'谭咏麟.png'
    },
    {
      name:'朋友',
      singer:'谭咏麟',
      duration:'04:48',
      music:'朋友.mp3',
      imgPath:'谭咏麟.png'
    },
    {
      name:'一生中最爱',
      singer:'谭咏麟',
      duration:'04:24',
      music:'爱多一次痛一次.mp3',
      imgPath:'谭咏麟.png'
    },
  ],
  [
    {
      name:'暧昧',
      singer:'薛之谦',
      duration:'05:12',
      music:'暧昧.mp3',
      imgPath:'薛之谦.png'
    },
    {
      name:'演员',
      singer:'薛之谦',
      duration:'04:21',
      music:'演员.mp3',
      imgPath:'薛之谦.png'
    },
    {
      name:'绅士',
      singer:'薛之谦',
      duration:'04:51',
      music:'绅士.mp3',
      imgPath:'薛之谦.png'
    },
    {
      name:'丑八怪',
      singer:'薛之谦',
      duration:'04:08',
      music:'丑八怪.mp3',
      imgPath:'薛之谦.png'
    },
  ],
  [
    {
      name:'如果·爱',
      singer:'张学友',
      duration:'03:53',
      music:'如果·爱.mp3',
      imgPath:'张学友.png'
    },
    {
      name:'留住这时光',
      singer:'张学友',
      duration:'04:35',
      music:'留住这时光.mp3',
      imgPath:'张学友.png'
    },
    {
      name:'她来听我的演唱会',
      singer:'张学友',
      duration:'04:51',
      music:'她来听我的演唱会.mp3',
      imgPath:'张学友.png'
    },
    {
      name:'只愿一生爱一人',
      singer:'张学友',
      duration:'04:22',
      music:'只愿一生爱一人.mp3',
      imgPath:'张学友.png'
    },
  ],
  [
    {
      name:'倾城',
      singer:'陈奕迅',
      duration:'04:09',
      music:'倾城.mp3',
      imgPath:'陈奕迅.png'
    },
    {
      name:'稳稳的幸福',
      singer:'陈奕迅',
      duration:'03:34',
      music:'稳稳的幸福.mp3',
      imgPath:'陈奕迅.png'
    },
    {
      name:'喜欢一个人(live)',
      singer:'陈奕迅',
      duration:'05:06',
      music:'喜欢一个人(live).mp3',
      imgPath:'陈奕迅.png'
    },
    {
      name:'不如不见',
      singer:'陈奕迅',
      duration:'04:09',
      music:'不如不见.mp3',
      imgPath:'陈奕迅.png'
    },
  ],
  [
      {
        name:'成都',
        singer:'赵雷',
        duration:'05:28',
        music:'成都.mp3',
        imgPath:'赵雷.png'
      },
      {
        name:'少年锦时',
        singer:'赵雷',
        duration:'05:08',
        music:'少年锦时.mp3',
        imgPath:'赵雷.png'
      },
      {
        name:'理想',
        singer:'赵雷',
        duration:'05:13',
        music:'理想.mp3',
        imgPath:'赵雷.png'
      },
      {
        name:'南方姑娘',
        singer:'赵雷',
        duration:'05:34',
        music:'南方姑娘.mp3',
        imgPath:'赵雷.png'
      },
    ],
]
// 歌手
var 周杰伦 = [
  {
    name:'晴天',
    singer:'周杰伦',
    duration:'04:48',
    music:'晴天.mp3',
    imgPath:'周杰伦.png'
  },
  {
    name:'夜的第七章',
    singer:'周杰伦',
    duration:'03:48',
    music:'夜的第七章.mp3',
    imgPath:'周杰伦.png'
  },
  {
    name:'半岛铁盒',
    singer:'周杰伦',
    duration:'05:19',
    music:'半岛铁盒.mp3',
    imgPath:'周杰伦.png'
  },
  {
    name:'东风破',
    singer:'周杰伦',
    duration:'05:15',
    music:'东风破.mp3',
    imgPath:'周杰伦.png'
  },
]

var 陈奕迅 = [
  {
    name:'倾城',
    singer:'陈奕迅',
    duration:'04:09',
    music:'倾城.mp3',
    imgPath:'陈奕迅.png'
  },
  {
    name:'稳稳的幸福',
    singer:'陈奕迅',
    duration:'03:34',
    music:'稳稳的幸福.mp3',
    imgPath:'陈奕迅.png'
  },
  {
    name:'喜欢一个人(live)',
    singer:'陈奕迅',
    duration:'05:06',
    music:'喜欢一个人(live).mp3',
    imgPath:'陈奕迅.png'
  },
  {
    name:'不如不见',
    singer:'陈奕迅',
    duration:'04:09',
    music:'不如不见.mp3',
    imgPath:'陈奕迅.png'
  },
]

var 李宗盛 = [
  {
    name:'凡人歌',
    singer:'李宗盛',
    duration:'03:46',
    music:'凡人歌.mp3',
    imgPath:'李宗盛.png'
  },
  {
    name:'鬼迷心窍',
    singer:'李宗盛',
    duration:'03:23',
    music:'鬼迷心窍.mp3',
    imgPath:'李宗盛.png'
  },
  {
    name:'不懂',
    singer:'李宗盛',
    duration:'03:04',
    music:'不懂.mp3',
    imgPath:'李宗盛.png'
  },
  {
    name:'问(live)',
    singer:'李宗盛',
    duration:'03:11',
    music:'问.mp3',
    imgPath:'李宗盛.png'
  },
]

var 林俊杰 = [
  {
    name:'江南',
    singer:'林俊杰',
    duration:'04:28',
    music:'江南.mp3',
    imgPath:'林俊杰.png'
  },
  {
    name:'她说',
    singer:'林俊杰',
    duration:'05:20',
    music:'她说.mp3',
    imgPath:'林俊杰.png'
  },
  {
    name:'爱笑的眼睛',
    singer:'林俊杰',
    duration:'04:13',
    music:'爱笑的眼睛.mp3',
    imgPath:'林俊杰.png'
  },
  {
    name:'当你',
    singer:'林俊杰',
    duration:'04:11',
    music:'当你.mp3',
    imgPath:'林俊杰.png'
  },
]

var 谭咏麟 = [
  {
    name:'爱多一次痛一次',
    singer:'谭咏麟',
    duration:'04:16',
    music:'爱多一次痛一次.mp3',
    imgPath:'谭咏麟.png'
  },
  {
    name:'再见亦是泪',
    singer:'谭咏麟',
    duration:'04:30',
    music:'再见亦是泪.mp3',
    imgPath:'谭咏麟.png'
  },
  {
    name:'朋友',
    singer:'谭咏麟',
    duration:'04:48',
    music:'朋友.mp3',
    imgPath:'谭咏麟.png'
  },
  {
    name:'一生中最爱',
    singer:'谭咏麟',
    duration:'04:24',
    music:'爱多一次痛一次.mp3',
    imgPath:'谭咏麟.png'
  },
]

var 薛之谦 = [
  {
    name:'暧昧',
    singer:'薛之谦',
    duration:'05:12',
    music:'暧昧.mp3',
    imgPath:'薛之谦.png'
  },
  {
    name:'演员',
    singer:'薛之谦',
    duration:'04:21',
    music:'演员.mp3',
    imgPath:'薛之谦.png'
  },
  {
    name:'绅士',
    singer:'薛之谦',
    duration:'04:51',
    music:'绅士.mp3',
    imgPath:'薛之谦.png'
  },
  {
    name:'丑八怪',
    singer:'薛之谦',
    duration:'04:08',
    music:'丑八怪.mp3',
    imgPath:'薛之谦.png'
  },
]

var 张学友 = [
  {
    name:'如果·爱',
    singer:'张学友',
    duration:'03:53',
    music:'如果·爱.mp3',
    imgPath:'张学友.png'
  },
  {
    name:'留住这时光',
    singer:'张学友',
    duration:'04:35',
    music:'留住这时光.mp3',
    imgPath:'张学友.png'
  },
  {
    name:'她来听我的演唱会',
    singer:'张学友',
    duration:'04:51',
    music:'她来听我的演唱会.mp3',
    imgPath:'张学友.png'
  },
  {
    name:'只愿一生爱一人',
    singer:'张学友',
    duration:'04:22',
    music:'只愿一生爱一人.mp3',
    imgPath:'张学友.png'
  },
]

var 赵雷 = [
  {
    name:'成都',
    singer:'赵雷',
    duration:'05:28',
    music:'成都.mp3',
    imgPath:'赵雷.png'
  },
  {
    name:'少年锦时',
    singer:'赵雷',
    duration:'05:08',
    music:'少年锦时.mp3',
    imgPath:'赵雷.png'
  },
  {
    name:'理想',
    singer:'赵雷',
    duration:'05:13',
    music:'理想.mp3',
    imgPath:'赵雷.png'
  },
  {
    name:'南方姑娘',
    singer:'赵雷',
    duration:'05:34',
    music:'南方姑娘.mp3',
    imgPath:'赵雷.png'
  },
]
